# Generated by Django 4.2.3 on 2024-05-31 05:41

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", markdownx.models.MarkdownxField()),
            ],
        ),
    ]
