# Generated by Django 4.2.3 on 2024-05-31 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Blog",
        ),
    ]
