# Generated by Django 4.2.3 on 2024-06-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_blogpost_content_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ManyToManyField(related_name="blogpost", to="main.category"),
        ),
    ]
