# Generated by Django 4.2.3 on 2024-06-01 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_blogpost_category_blogimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogimage",
            old_name="image",
            new_name="blog_image",
        ),
    ]
