# Generated by Django 4.2.3 on 2024-06-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_image_blogimage_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimage",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_images",
                to="main.blogpost",
            ),
        ),
    ]
